[package]
name = "lychrel"
version = "0.1.0"
authors = ["Alessio Sanfratello <sanfra90@gmail.com>"]
edition = "2018"

[dependencies]
pyo3 = { version = "0.13", features = ["extension-module", "abi3-py36"] }

[lib]
name = "lychrel"
crate-type = ["cdylib"]

[package.metadata.maturin]
requires-python = ">=3.6"
requires-dist = [
]
classifier = [
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Rust",
]