[package]
name = "lychrel"
version = "0.8.0"
homepage = "https://github.com/alesanfra/lychrel"
edition = "2021"

[lib]
name = "lychrel"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "*", features = ["num-bigint", "extension-module", "abi3-py37"] }
num-traits = "*"
num-bigint = "*"
