name: Build

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        python-version: [ "3.6", "3.7", "3.8", "3.9", "3.10" ]
        os: [ ubuntu-latest, macos-latest]
    name: Build on ${{ matrix.os }} - python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
      - name: Build wheels
        uses: messense/maturin-action@v1
        with:
          manylinux: auto
          args: -i python${{ matrix.python-version }} --release --strip --universal2 --out dist --no-sdist
      - name: Install built wheel
        run: |
          pip install lychrel --no-index --find-links dist --force-reinstall
          python -I -c "import lychrel"
      - name: Run tests
        run: |
          pip install -r requirements-dev.txt
          pytest
      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist

  release:
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          skip_existing: true